# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=0.1.0
mod.group=com.example
mod.id=template
mod.name=Template Mod

publish.modrinth=# Modrinth mod slug
publish.curseforge=# Curseforge numeric mod ID
